export type Language = "zh" | "en";

export const translations = {
  zh: {
    // Header
    "ai_assistant": "AI 房地產詢問助理",
    "dashboard": "儀表板",
    "sync_facebook": "同步 Facebook",
    "facebook_connected": "Facebook 已連接",
    "facebook_not_connected": "Facebook 未連接",

    // Chat
    "select_conversation": "選擇對話",
    "select_from_left": "從左側選擇一個買家對話開始",
    "enter_message": "輸入買家訊息... (Enter 送出，Shift+Enter 換行)",
    "analyze": "分析對話",

    // Input
    "ai_analysis_summary": "AI 分析摘要",
    "suggested_replies": "建議回覆",
    "option": "選項",

    // Analysis Panel
    "ai_assistant_panel": "AI 助理",
    "needs_followup": "需要追蹤",
    "buyer_inactive": "買家已",
    "hours_inactive": "小時未回覆",
    "generate_followup": "生成追蹤建議",
    "followup_suggestions": "追蹤建議",
    "quick_reply": "快速回覆",
    "conversation_summary": "對話摘要",
    "refresh": "刷新",
    "generate_summary": "點擊刷新按鈕生成對話摘要",
    "customer_hotness": "客戶熱度",
    "reason": "原因",
    "suggested_followup": "建議跟進：",
    "days_later": "天後",
    "buyer_info": "買家資料",
    "budget": "預算",
    "location": "地點",
    "property_type": "物業類型",
    "purpose": "用途",
    "timeline": "時間表",
    "auto_followup": "自動追蹤",
    "auto_followup_desc": "12小時未回覆自動發送追蹤",

    // Quick Reply Categories
    "quick_reply_price": "價格查詢",
    "quick_reply_inspection": "檢驗安排",
    "quick_reply_property_info": "物業資訊",
    "quick_reply_contract": "合約詢問",
    "quick_reply_general": "一般回覆",

    // Toasts
    "sync_complete": "同步完成",
    "sync_complete_desc": "已從 Facebook 同步對話",
    "sync_failed": "同步失敗",
    "message_sent_failed": "發送訊息失敗",
    "message_sent_error": "無法發送訊息，請稍後再試",
    "ai_analysis_complete": "AI 分析完成",
    "analysis_failed": "AI 分析失敗",
    "analysis_error": "無法分析對話，請稍後再試",
    "hot_lead": "熱客戶",
    "warm_lead": "溫客戶",
    "cold_lead": "冷客戶",

    // Dashboard
    "action_dashboard": "行動儀表板",
    "needs_followup_tab": "需要追蹤",
    "hot_leads_tab": "熱客戶",
    "unread_tab": "未讀",
    "stats": "統計",
    "total_conversations": "總對話數",
    "hot_leads_count": "熱客戶",
    "warm_leads_count": "溫客戶",
    "cold_leads_count": "冷客戶",
    "avg_response_time": "平均回應時間",
    "hours": "小時",
    "no_results": "沒有結果",

    // Listings
    "listings": "物業清單",
    "add_listing": "新增物業",
    "linked_listings": "關聯物業",
    "primary_listing": "主要物業",
    "set_as_primary": "設為主要",
    "remove_listing": "移除物業",
    "no_listings": "尚未關聯物業",
    "add_first_listing": "點擊新增物業",
    "select_listing": "選擇物業",
    "suggest_property": "建議物業",
    "create_new_listing": "建立新物業",
    "listing_title": "物業標題",
    "listing_address": "地址",
    "listing_price": "價格指南",
    "save_listing": "儲存物業",
    "cancel": "取消",
    "listing_linked": "物業已關聯",
    "listing_unlinked": "物業已移除",
    "listing_created": "物業已建立",
    "using_listing": "使用物業：",
    "select_property": "選擇物業以生成回覆",
    "multiple_listings": "多個物業",
    "which_property": "此對話關聯多個物業，請選擇要使用的物業：",

    // Property Carousel
    "recommended_properties": "推薦物業",
    "ai_recommends": "AI 推薦",
    "get_ai_recommendations": "取得 AI 推薦",
    "loading_recommendations": "正在分析買家需求...",
    "no_properties_yet": "尚未新增物業",
    "add_property_to_start": "點擊新增物業開始",
    "bedrooms_short": "房",
    "bathrooms_short": "衛",
    "parking_short": "車位",
    "view_contract": "查看合約",
    "available_inspection": "可預約時間",
    "property_details": "物業詳情",

    // Property Modal Fields
    "contract_link": "合約連結",
    "contract_link_placeholder": "https://example.com/contract.pdf",
    "inspection_available_date": "可預約看房日期",
    "inspection_available_time": "可預約時段",
    "inspection_time_placeholder": "例如：10:00-12:00, 14:00-16:00",
    "strata_fee": "管理費",
    "bedrooms": "房間數",
    "bathrooms": "衛浴數",
    "parking": "車位",
    "agent_name": "經紀人姓名",
    "agent_mobile": "經紀人電話",
    "quick_actions": "快速操作",
  },
  en: {
    // Header
    "ai_assistant": "AI Real Estate Assistant",
    "dashboard": "Dashboard",
    "sync_facebook": "Sync Facebook",
    "facebook_connected": "Facebook Connected",
    "facebook_not_connected": "Facebook Not Connected",

    // Chat
    "select_conversation": "Select Conversation",
    "select_from_left": "Select a buyer conversation from the left to start",
    "enter_message": "Enter buyer message... (Enter to send, Shift+Enter for new line)",
    "analyze": "Analyze Conversation",

    // Input
    "ai_analysis_summary": "AI Analysis Summary",
    "suggested_replies": "Suggested Replies",
    "option": "Option",

    // Analysis Panel
    "ai_assistant_panel": "AI Assistant",
    "needs_followup": "Needs Follow-up",
    "buyer_inactive": "Buyer inactive for",
    "hours_inactive": "hours",
    "generate_followup": "Generate Follow-up Suggestions",
    "followup_suggestions": "Follow-up Suggestions",
    "quick_reply": "Quick Reply",
    "conversation_summary": "Conversation Summary",
    "refresh": "Refresh",
    "generate_summary": "Click refresh to generate conversation summary",
    "customer_hotness": "Lead Temperature",
    "reason": "Reason",
    "suggested_followup": "Suggested Follow-up: ",
    "days_later": "days",
    "buyer_info": "Buyer Information",
    "budget": "Budget",
    "location": "Location",
    "property_type": "Property Type",
    "purpose": "Purpose",
    "timeline": "Timeline",
    "auto_followup": "Auto Follow-up",
    "auto_followup_desc": "Automatically send follow-up after 12 hours of no response",

    // Quick Reply Categories
    "quick_reply_price": "Price Inquiry",
    "quick_reply_inspection": "Inspection Schedule",
    "quick_reply_property_info": "Property Information",
    "quick_reply_contract": "Contract Inquiry",
    "quick_reply_general": "General Reply",

    // Toasts
    "sync_complete": "Sync Complete",
    "sync_complete_desc": "Conversations synced from Facebook",
    "sync_failed": "Sync Failed",
    "message_sent_failed": "Message Send Failed",
    "message_sent_error": "Unable to send message, please try again later",
    "ai_analysis_complete": "AI Analysis Complete",
    "analysis_failed": "AI Analysis Failed",
    "analysis_error": "Unable to analyze conversation, please try again later",
    "hot_lead": "Hot Lead",
    "warm_lead": "Warm Lead",
    "cold_lead": "Cold Lead",

    // Dashboard
    "action_dashboard": "Action Dashboard",
    "needs_followup_tab": "Needs Follow-up",
    "hot_leads_tab": "Hot Leads",
    "unread_tab": "Unread",
    "stats": "Statistics",
    "total_conversations": "Total Conversations",
    "hot_leads_count": "Hot Leads",
    "warm_leads_count": "Warm Leads",
    "cold_leads_count": "Cold Leads",
    "avg_response_time": "Avg Response Time",
    "hours": "hours",
    "no_results": "No Results",

    // Listings
    "listings": "Property Listings",
    "add_listing": "Add Property",
    "linked_listings": "Linked Properties",
    "primary_listing": "Primary Property",
    "set_as_primary": "Set as Primary",
    "remove_listing": "Remove Property",
    "no_listings": "No properties linked",
    "add_first_listing": "Click to add property",
    "select_listing": "Select Listing",
    "suggest_property": "Suggest Property",
    "create_new_listing": "Create New Property",
    "listing_title": "Property Title",
    "listing_address": "Address",
    "listing_price": "Price Guide",
    "save_listing": "Save Property",
    "cancel": "Cancel",
    "listing_linked": "Property Linked",
    "listing_unlinked": "Property Removed",
    "listing_created": "Property Created",
    "using_listing": "Using property:",
    "select_property": "Select property to generate reply",
    "multiple_listings": "Multiple Properties",
    "which_property": "This conversation has multiple linked properties. Please select which one to use:",

    // Property Carousel
    "recommended_properties": "Recommended Properties",
    "ai_recommends": "AI Recommends",
    "get_ai_recommendations": "Get AI Recommendations",
    "loading_recommendations": "Analyzing buyer needs...",
    "no_properties_yet": "No properties added yet",
    "add_property_to_start": "Click to add property",
    "bedrooms_short": "bed",
    "bathrooms_short": "bath",
    "parking_short": "parking",
    "view_contract": "View Contract",
    "available_inspection": "Available Times",
    "property_details": "Property Details",

    // Property Modal Fields
    "contract_link": "Contract Link",
    "contract_link_placeholder": "https://example.com/contract.pdf",
    "inspection_available_date": "Available Inspection Date",
    "inspection_available_time": "Available Time Slots",
    "inspection_time_placeholder": "e.g., 10:00-12:00, 14:00-16:00",
    "strata_fee": "Strata Fee",
    "bedrooms": "Bedrooms",
    "bathrooms": "Bathrooms",
    "parking": "Parking",
    "agent_name": "Agent Name",
    "agent_mobile": "Agent Mobile",
    "quick_actions": "Quick Actions",
  }
};

export function getTranslation(lang: Language, key: keyof typeof translations.zh): string {
  return translations[lang][key] || translations.zh[key];
}